### ISSUE TITLE
Getting this to work post heroku migration?

### ISSUE THREAD

**Issue by kokernutz** [layerhq/layer-parse-module#7]
I'm at a loss as to how to get this to work after migrating my app to heroku.

I added it to my parse-server-example repo and pushed it to heroku, and verified that it was present by checking the slug with a heroku run bash. I don't know where to go from here. I'm a heroku/node n00b.

```
2016-05-02T12:01:14.084959+00:00 app[web.1]: Error: Cannot find module 'cloud/layer-parse-module/layer-module.js'
2016-05-02T12:01:14.084960+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-05-02T12:01:14.084961+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-05-02T12:01:14.084962+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-05-02T12:01:14.084962+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-05-02T12:01:14.084963+00:00 app[web.1]:     at Object.<anonymous> (/app/cloud/main.js:2:13)
2016-05-02T12:01:14.084964+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-05-02T12:01:14.084965+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-05-02T12:01:14.084965+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-05-02T12:01:14.084966+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-05-02T12:01:14.084970+00:00 app[web.1]:     at Module.require (module.js:367:17)
```

**Comment by kokernutz** [comment]
Figured it out.

**Comment by HananeAlSamrout** [comment]
how?
